/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.ListaRegistros;

/**
 *
 * @author Micro
 */
public class VisualizarGraficos extends javax.swing.JFrame {
    
    
    private final ListaRegistros lr;
    /**
     * Creates new form VisualizarGraficos
     * @param lr
     */
    public VisualizarGraficos(ListaRegistros lr) {
        initComponents();
  
        this.lr = lr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCPU = new javax.swing.JButton();
        BtnHD = new javax.swing.JButton();
        BtnRAM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        BtnCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CPU-Z-icon.png"))); // NOI18N
        BtnCPU.setText("Visualizar Uso da CPU");
        BtnCPU.setMaximumSize(new java.awt.Dimension(200, 70));
        BtnCPU.setMinimumSize(new java.awt.Dimension(200, 70));
        BtnCPU.setPreferredSize(new java.awt.Dimension(200, 70));
        BtnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCPUActionPerformed(evt);
            }
        });

        BtnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Devices-drive-harddisk-icon.png"))); // NOI18N
        BtnHD.setText("Visualizar Uso do HD");
        BtnHD.setMaximumSize(new java.awt.Dimension(200, 70));
        BtnHD.setMinimumSize(new java.awt.Dimension(200, 70));
        BtnHD.setPreferredSize(new java.awt.Dimension(200, 70));
        BtnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHDActionPerformed(evt);
            }
        });

        BtnRAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory-icon.png"))); // NOI18N
        BtnRAM.setText("Visualizar Uso da RAM");
        BtnRAM.setMaximumSize(new java.awt.Dimension(200, 70));
        BtnRAM.setMinimumSize(new java.awt.Dimension(200, 70));
        BtnRAM.setPreferredSize(new java.awt.Dimension(200, 70));
        BtnRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRAMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Performace");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 70));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 70));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRAMActionPerformed
        GraficoRAM gr = new GraficoRAM(lr);
        gr.setVisible(true);
    }//GEN-LAST:event_BtnRAMActionPerformed

    private void BtnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCPUActionPerformed
        GraficoCPU gc = new GraficoCPU(lr);
        gc.setVisible(true);
    }//GEN-LAST:event_BtnCPUActionPerformed

    private void BtnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHDActionPerformed
        GraficoHD gh = new GraficoHD(lr);
        gh.setVisible(true);
    }//GEN-LAST:event_BtnHDActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VisualizarGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VisualizarGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VisualizarGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VisualizarGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VisualizarGraficos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCPU;
    private javax.swing.JButton BtnHD;
    private javax.swing.JButton BtnRAM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
